# Generated by Django 5.1.3 on 2025-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=255, verbose_name='العنصر [عربية]')),
                ('text_en', models.CharField(max_length=255, verbose_name='العنصر [إنجليزية]')),
            ],
            options={
                'verbose_name': 'عنصر مصفوفة',
                'verbose_name_plural': 'عناصر المصفوفة',
            },
        ),
        migrations.CreateModel(
            name='MatrixItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('items', models.ManyToManyField(to='Qbank.matrixitem', verbose_name='العناصر')),
            ],
            options={
                'verbose_name': 'مجموعة عناصر مصفوفة',
                'verbose_name_plural': 'مجموعات عناصر المصفوفة',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(verbose_name='السؤال [عربية]')),
                ('text_en', models.TextField(verbose_name='السؤال [إنجليزية]')),
                ('response_groups', models.ManyToManyField(related_name='questions', to='Rbank.responsegroup', verbose_name='مجموعات الإجابات')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
    ]
