# Generated by Django 5.1.3 on 2025-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'verbose_name': 'سؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
    ]
