# Generated by Django 5.1.3 on 2025-12-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Qbank', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstaging',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_questions', to='surveys.survey', verbose_name='الاستبيان'),
        ),
        migrations.AddField(
            model_name='questionstaging',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
    ]
