# Generated by Django 5.1.3 on 2025-12-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0001_initial'),
        ('surveys', '0003_remove_surveyquestion_section_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(blank=True, verbose_name='السؤال المقترح [عربية]')),
                ('text_en', models.TextField(blank=True, verbose_name='السؤال المقترح [إنجليزية]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_questions', to='surveys.survey', verbose_name='الاستبيان')),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'سؤال قيد الإعداد',
                'verbose_name_plural': 'أسئلة قيد الإعداد',
            },
        ),
    ]
