# Generated by Django 5.1.3 on 2025-12-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0002_questionstaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstaging',
            name='is_sent_for_translation',
            field=models.BooleanField(default=False, verbose_name='مرسل للترجمة'),
        ),
    ]
