# Generated by Django 5.2.8 on 2025-12-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=255, verbose_name='السؤال [عربية]')),
                ('text_en', models.CharField(max_length=255, verbose_name='السؤال [إنجليزية]')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'إجابات',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نوع الاستجابة (مثل اختيار واحد أو رقمي).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'نوع الاستجابة',
                'verbose_name_plural': 'أنواع الاستجابة',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(verbose_name='السؤال [عربية]')),
                ('text_en', models.TextField(verbose_name='السؤال [إنجليزية]')),
                ('possible_responses', models.ManyToManyField(blank=True, help_text='حدد الإجابات المحتملة لأسئلة الاختيار.', related_name='questions', to='QnR.response')),
                ('response_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='QnR.responsetype')),
            ],
            options={
                'verbose_name': 'سؤال استبيان',
                'verbose_name_plural': 'أسئلة الاستبيان',
            },
        ),
    ]
