# Generated by Django 5.2.8 on 2025-12-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=255, verbose_name='Text in Arabic')),
                ('text_en', models.CharField(max_length=255, verbose_name='Text in English')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The type of response (e.g., Single Choice, Numeric).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Response Type',
                'verbose_name_plural': 'Response Types',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(verbose_name='Text in Arabic')),
                ('text_en', models.TextField(verbose_name='Text in English')),
                ('possible_responses', models.ManyToManyField(blank=True, help_text='Select possible responses for choice-based questions.', related_name='questions', to='QnR.response')),
                ('response_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='QnR.responsetype')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
            },
        ),
    ]
