# Generated by Django 5.2.8 on 2025-12-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text_ar',
            field=models.CharField(max_length=255, verbose_name='الجواب [عربية]'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text_en',
            field=models.CharField(max_length=255, verbose_name='الجواب [إنجليزية]'),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نوع الاستجابة'),
        ),
    ]
