# Generated by Django 5.2.8 on 2025-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0002_alter_response_text_ar_alter_response_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('responses', models.ManyToManyField(to='QnR.response', verbose_name='الإجابات')),
            ],
            options={
                'verbose_name': 'مجموعة إجابات',
                'verbose_name_plural': 'مجموعات الإجابات',
            },
        ),
    ]
