# Generated by Django 5.2.8 on 2025-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0003_responsegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetype',
            name='name',
        ),
        migrations.AddField(
            model_name='responsetype',
            name='name_ar',
            field=models.CharField(default='asd', max_length=100, unique=True, verbose_name='نوع الاستجابة [عربية]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsetype',
            name='name_en',
            field=models.CharField(default='asdad', max_length=100, unique=True, verbose_name='نوع الاستجابة [إنجليزية]'),
            preserve_default=False,
        ),
    ]
