# Generated by Django 5.2.8 on 2025-12-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0004_remove_responsetype_name_responsetype_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsegroup',
            options={'verbose_name': 'مجموعة الإجابات', 'verbose_name_plural': 'مجموعات الإجابات'},
        ),
    ]
