# Generated by Django 5.2.8 on 2025-12-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0005_alter_responsegroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsegroup',
            options={'verbose_name': 'مجموعة إجابات', 'verbose_name_plural': 'مجموعات الإجابات'},
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='possible_responses',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='response_type',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='response_group',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='QnR.responsegroup', verbose_name='مجموعة الإجابات'),
            preserve_default=False,
        ),
    ]
