# Generated by Django 5.2.8 on 2025-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0006_alter_responsegroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='response_group',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='response_groups',
            field=models.ManyToManyField(related_name='questions', to='QnR.responsegroup', verbose_name='مجموعات الإجابات'),
        ),
    ]
