# Generated by Django 5.2.9 on 2025-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnR', '0007_remove_surveyquestion_response_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsegroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المجموعة'),
        ),
    ]
