# Generated by Django 5.2.8 on 2025-12-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the indicator.', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional code, e.g. IND_01 or SDG_8_5_2.', max_length=50)),
                ('classification', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('INTERNATIONAL', 'International')], default='NATIONAL', help_text='Classification of the indicator.', max_length=20)),
                ('unit', models.CharField(blank=True, help_text="Unit of measure, e.g. % or 'persons'.", max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='Frequency of publication, e.g. monthly, quarterly.', max_length=50)),
                ('methodology_reference', models.URLField(blank=True, help_text='Optional URL to methodology or metadata documentation.')),
                ('notes', models.TextField(blank=True, help_text='Free-form notes or methodological comments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the indicator list item.', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional code for the list item.', max_length=50)),
                ('tracking_status', models.CharField(blank=True, choices=[('TRACKED', 'Tracked by the authority'), ('NOT_TRACKED', 'Not tracked by the authority')], help_text='Whether this specific item is tracked by the authority.', max_length=20, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indicators.indicator')),
                ('survey_question', models.ForeignKey(blank=True, help_text='Survey question that defines or feeds this indicator list item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyquestion')),
                ('survey_version', models.ForeignKey(blank=True, help_text='Survey version this indicator list item is defined on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('indicator', 'name')},
            },
        ),
    ]
