# Generated by Django 5.1.3 on 2025-12-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='الاسم [عربية]')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='الاسم [إنجليزية]')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='الاسم [عربية]')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='الاسم [إنجليزية]')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الرمز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'المؤشر',
                'verbose_name_plural': 'المؤشرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم عنصر قائمة المؤشر.', max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(blank=True, help_text='رمز اختياري لعنصر القائمة.', max_length=50, verbose_name='الرمز')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indicators.indicator', verbose_name='المؤشر')),
            ],
            options={
                'verbose_name': 'اسم المؤشر',
                'verbose_name_plural': 'أسماء المؤشرات',
                'ordering': ['id'],
                'unique_together': {('indicator', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationIndicatorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.classification')),
                ('indicatorlistitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicatorlistitem', verbose_name='اسم المؤشر')),
            ],
            options={
                'verbose_name': 'عنصر قائمة مؤشر التصنيف',
                'verbose_name_plural': 'عناصر قائمة مؤشر التصنيف',
            },
        ),
        migrations.CreateModel(
            name='IndicatorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRACKED', 'متابع'), ('NOT_TRACKED', 'غير متابع')], max_length=20, verbose_name='الحالة')),
                ('indicator_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='indicators.indicatorlistitem', verbose_name='عنصر قائمة المؤشر')),
            ],
            options={
                'verbose_name': 'تتبع المؤشر',
                'verbose_name_plural': 'معلومات تتبع المؤشر',
            },
        ),
        migrations.CreateModel(
            name='IndicatorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.classification', verbose_name='التصنيف')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='indicators.indicator', verbose_name='المؤشر')),
            ],
            options={
                'verbose_name': 'تصنيف المؤشر',
                'verbose_name_plural': 'تصنيفات المؤشر',
                'unique_together': {('indicator', 'classification')},
            },
        ),
    ]
