# Generated by Django 5.1.3 on 2025-12-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='الاسم [عربية]')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='الاسم [إنجليزية]')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الرمز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مصدر المؤشر',
                'verbose_name_plural': 'مصادر المؤشرات',
                'ordering': ['code'],
            },
        ),
    ]
