# Generated by Django 5.1.3 on 2025-12-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='المؤشر [عربية]')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='المؤشر [إنجليزية]')),
                ('code', models.CharField(blank=True, help_text='رمز اختياري للمؤشر.', max_length=50, verbose_name='الرمز')),
                ('tracking_status', models.CharField(choices=[('TRACKED', 'متابع'), ('NOT_TRACKED', 'غير متابع')], default='NOT_TRACKED', max_length=20, verbose_name='حالة التتبع')),
                ('indicator_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indicators.indicatorsource', verbose_name='مصدر المؤشر')),
            ],
            options={
                'verbose_name': 'المؤشر',
                'verbose_name_plural': 'المؤشرات',
                'ordering': ['id'],
                'unique_together': {('indicator_source', 'name_ar')},
            },
        ),
    ]
