# Generated by Django 5.1.3 on 2025-12-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('surveys', '0003_alter_survey_options_remove_survey_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlistitem',
            name='survey_question',
            field=models.ForeignKey(blank=True, help_text='سؤال الاستبيان الذي يعرّف أو يرفد هذا العنصر.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان'),
        ),
        migrations.AddField(
            model_name='indicatorlistitem',
            name='survey_version',
            field=models.ForeignKey(blank=True, help_text='نسخة الاستبيان التي يُعرَّف عليها هذا العنصر.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='الاسم [عربية]'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='الاسم [إنجليزية]'),
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='القاعدة (JSON)')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='indicators.classification')),
            ],
            options={
                'verbose_name': 'قاعدة التصنيف',
                'verbose_name_plural': 'قواعد التصنيف',
            },
        ),
        migrations.DeleteModel(
            name='ClassificationIndicatorListItem',
        ),
    ]
