# Generated by Django 5.2.8 on 2025-12-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('surveys', '0006_alter_surveyquestion_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['-created_at'], 'verbose_name': 'المؤشر', 'verbose_name_plural': 'المؤشرات'},
        ),
        migrations.AlterModelOptions(
            name='indicatorlistitem',
            options={'ordering': ['id'], 'verbose_name': 'عنصر قائمة المؤشر', 'verbose_name_plural': 'عناصر قائمة المؤشر'},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='methodology_reference',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='unit',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='classification',
            field=models.CharField(choices=[('NATIONAL', 'وطني'), ('REGIONAL', 'إقليمي'), ('INTERNATIONAL', 'دولي')], default='NATIONAL', help_text='تصنيف المؤشر.', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(help_text='اسم المؤشر المقروء.', max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='code',
            field=models.CharField(blank=True, help_text='رمز اختياري لعنصر القائمة.', max_length=50, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indicators.indicator', verbose_name='المؤشر'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='name',
            field=models.CharField(help_text='اسم عنصر قائمة المؤشر.', max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='survey_question',
            field=models.ForeignKey(blank=True, help_text='سؤال الاستبيان الذي يعرّف أو يرفد هذا العنصر.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='survey_version',
            field=models.ForeignKey(blank=True, help_text='نسخة الاستبيان التي يُعرَّف عليها هذا العنصر.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_list_items', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
        migrations.AlterField(
            model_name='indicatorlistitem',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('TRACKED', 'متابع من الجهة المختصة'), ('NOT_TRACKED', 'غير متابع من الجهة المختصة')], help_text='ما إذا كان هذا العنصر متابعاً من الجهة المختصة.', max_length=20, null=True, verbose_name='حالة التتبع'),
        ),
    ]
