# Generated by Django 5.1.3 on 2025-12-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='code',
        ),
    ]
