# Generated by Django 5.2.8 on 2025-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(default='2sfdsfs', help_text='اسم المؤشر المقروء.', max_length=255, verbose_name='الاسم [عربية]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(default='asfsadfsdfsdfxd', help_text='اسم المؤشر المقروء.', max_length=255, verbose_name='الاسم [إنجليزية]'),
            preserve_default=False,
        ),
    ]
