# Generated by Django 5.1.3 on 2025-12-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_indicatorlistitem_survey_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorlistitem',
            name='survey_question',
        ),
        migrations.RemoveField(
            model_name='indicatorlistitem',
            name='survey_version',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم [عربية]'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم [إنجليزية]'),
        ),
        migrations.CreateModel(
            name='ClassificationIndicatorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.classification')),
                ('indicatorlistitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicatorlistitem', verbose_name='اسم المؤشر')),
            ],
            options={
                'verbose_name': 'عنصر قائمة مؤشر التصنيف',
                'verbose_name_plural': 'عناصر قائمة مؤشر التصنيف',
            },
        ),
        migrations.DeleteModel(
            name='ClassificationRule',
        ),
    ]
