# Generated by Django 5.1.3 on 2025-12-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_remove_indicatorlistitem_survey_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='قاعدة التصنيف')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='indicators.classification')),
            ],
            options={
                'verbose_name': 'قاعدة التصنيف',
                'verbose_name_plural': 'قواعد التصنيف',
            },
        ),
        migrations.DeleteModel(
            name='ClassificationIndicatorListItem',
        ),
    ]
