# Generated by Django 5.2.8 on 2025-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_remove_indicator_name_indicator_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='الاسم [عربية]'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='الاسم [إنجليزية]'),
        ),
    ]
