# Generated by Django 5.2.8 on 2025-12-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_indicator_name_ar_alter_indicator_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='indicatorlistitem',
            name='tracking_status',
        ),
        migrations.CreateModel(
            name='IndicatorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRACKED', 'متابع'), ('NOT_TRACKED', 'غير متابع')], max_length=20, verbose_name='الحالة')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='indicators.indicator', verbose_name='المؤشر')),
            ],
            options={
                'verbose_name': 'تتبع المؤشر',
                'verbose_name_plural': 'معلومات تتبع المؤشر',
            },
        ),
        migrations.CreateModel(
            name='IndicatorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('NATIONAL', 'وطني'), ('REGIONAL', 'إقليمي'), ('INTERNATIONAL', 'دولي')], max_length=20, verbose_name='التصنيف')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='indicators.indicator', verbose_name='المؤشر')),
            ],
            options={
                'verbose_name': 'تصنيف المؤشر',
                'verbose_name_plural': 'تصنيفات المؤشر',
                'unique_together': {('indicator', 'classification')},
            },
        ),
    ]
