# Generated by Django 5.2.8 on 2025-12-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_remove_indicator_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.AlterField(
            model_name='indicatorclassification',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.classification', verbose_name='التصنيف'),
        ),
    ]
