# Generated by Django 5.2.8 on 2025-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='name',
        ),
        migrations.AddField(
            model_name='classification',
            name='items',
            field=models.ManyToManyField(to='indicators.indicatorlistitem', verbose_name='عناصر قائمة المؤشر'),
        ),
        migrations.AddField(
            model_name='classification',
            name='name_ar',
            field=models.CharField(default='سيشيشسيش', max_length=100, unique=True, verbose_name='الاسم [عربية]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='name_en',
            field=models.CharField(default='dasdasdas', max_length=100, unique=True, verbose_name='الاسم [إنجليزية]'),
            preserve_default=False,
        ),
    ]
