# Generated by Django 5.2.8 on 2025-12-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_remove_classification_name_classification_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorlistitem',
            options={'ordering': ['id'], 'verbose_name': 'اسم المؤشر', 'verbose_name_plural': 'أسماء المؤشرات'},
        ),
    ]
