# Generated by Django 5.2.8 on 2025-12-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_alter_indicatorlistitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='items',
        ),
        migrations.CreateModel(
            name='ClassificationIndicatorListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.classification')),
                ('indicatorlistitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicatorlistitem', verbose_name='اسم المؤشر')),
            ],
            options={
                'verbose_name': 'عنصر قائمة مؤشر التصنيف',
                'verbose_name_plural': 'عناصر قائمة مؤشر التصنيف',
            },
        ),
    ]
