# Generated by Django 5.2.8 on 2025-12-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_remove_classification_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatortracking',
            name='indicator',
        ),
        migrations.AddField(
            model_name='indicatortracking',
            name='indicator_list_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='indicators.indicatorlistitem', verbose_name='عنصر قائمة المؤشر'),
            preserve_default=False,
        ),
    ]
