# Generated by Django 5.2.8 on 2025-12-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_remove_indicatortracking_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorlistitem',
            name='survey_question',
        ),
        migrations.RemoveField(
            model_name='indicatorlistitem',
            name='survey_version',
        ),
    ]
