# Generated by Django 5.2.9 on 2025-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_remove_indicatorlistitem_survey_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم [عربية]'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم [إنجليزية]'),
        ),
    ]
