# Generated by Django 5.2.8 on 2025-12-12 19:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(blank=True, help_text='رمز قصير اختياري مثل LFS_2025.', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='يُنشأ تلقائياً من الاسم إذا تُرك فارغاً.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', help_text='مسودة: قيد التصميم. نشط: قيد الاستخدام. مؤرشف: لم يعد مستخدماً.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editors', models.ManyToManyField(blank=True, help_text='المستخدمون المسموح لهم بتعديل هيكل الاستبيان.', related_name='editable_surveys', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='المسؤول الأساسي عن هذا الاستبيان.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, help_text="تسمية ودية مثل '2025-03' أو 'الجولة 1-2025'.", max_length=50)),
                ('version_date', models.DateField(default=datetime.date.today, help_text='تاريخ الإشارة لهذه النسخة/الموجة.')),
                ('interval', models.CharField(choices=[('M', 'شهري'), ('Q', 'ربع سنوي'), ('B', 'نصف سنوي'), ('A', 'سنوي')], help_text='تواتر الاستبيان.', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('LOCKED', 'مقفل'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', help_text='مسودة: قابلة للتحرير؛ نشطة: قيد الجمع؛ مقفلة: هيكل ثابت؛ مؤرشفة: للاطلاع التاريخي.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='بيانات وصفية اختيارية مثل معلومات إطار العينة أو الملاحظات.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey')),
            ],
            options={
                'ordering': ['-version_date', '-id'],
                'unique_together': {('survey', 'version_label')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='رمز سؤال اختياري مثل Q1 أو A01.', max_length=50)),
                ('text', models.TextField(help_text='النص الكامل للسؤال كما يراه المجيب.')),
                ('text_ar', models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة العربية.', verbose_name='السؤال [عربية]')),
                ('text_en', models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة الإنجليزية.', verbose_name='السؤال [إنجليزية]')),
                ('help_text', models.TextField(blank=True, help_text='نص مساعدة اختياري أو تعليمات للمُعِد.')),
                ('section_label', models.CharField(blank=True, help_text='تسمية قسم منطقية للتقارير فقط.', max_length=255)),
                ('response_type', models.CharField(choices=[('BINARY', 'نعم/لا (ثنائي)'), ('SINGLE_CHOICE', 'اختيار واحد'), ('MULTIPLE_CHOICE', 'اختيارات متعددة'), ('FREE_TEXT', 'نص حر'), ('NUMERIC', 'رقمي'), ('DATE', 'تاريخ'), ('DATETIME', 'تاريخ ووقت'), ('SCALE', 'مقياس (مثلاً 1–5)'), ('MATRIX', 'مصفوفة')], default='FREE_TEXT', help_text='النوع الأساسي المتوقع للإجابة؛ يمكن أن تعيش الترميزات أو التحقق التفصيلي في مكان آخر.', max_length=30)),
                ('is_required', models.BooleanField(default=False, help_text='هل يجب الإجابة على السؤال أثناء جمع البيانات.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='بنية إضافية اختيارية (القيم المسموحة، النطاقات، شروط التخطي، إلخ).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
