# Generated by Django 5.1.3 on 2025-12-28 20:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='اسم المسح [عربية]')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='اسم المسح [انجليزية]')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استبيان',
                'verbose_name_plural': 'الاستبيانات',
                'ordering': ['name_ar', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, editable=False, max_length=50)),
                ('version_date', models.DateField(default=datetime.date.today, help_text='تاريخ الإشارة لهذه النسخة/الموجة.', verbose_name='تاريخ الإصدار')),
                ('interval', models.CharField(choices=[('M', 'شهري'), ('Q', 'ربع سنوي'), ('B', 'نصف سنوي'), ('A', 'سنوي')], help_text='تواتر الاستبيان.', max_length=20, verbose_name='الفاصل الزمني')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('LOCKED', 'مقفل'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', help_text='مسودة: قابلة للتحرير؛ نشطة: قيد الجمع؛ مقفلة: هيكل ثابت؛ مؤرشفة: للاطلاع التاريخي.', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey', verbose_name='الاستبيان')),
            ],
            options={
                'verbose_name': 'إصدار الاستبيان',
                'verbose_name_plural': 'إصدارات الاستبيان',
                'ordering': ['-version_date', '-id'],
                'unique_together': {('survey', 'version_label')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='رمز سؤال اختياري مثل Q1 أو A01.', max_length=50, verbose_name='الرمز')),
                ('text_ar', models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة العربية.', verbose_name='السؤال [عربية]')),
                ('text_en', models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة الإنجليزية.', verbose_name='السؤال [إنجليزية]')),
                ('help_text', models.TextField(blank=True, help_text='نص مساعدة اختياري أو تعليمات للمُعِد.')),
                ('is_required', models.BooleanField(default=False, help_text='هل يجب الإجابة على السؤال أثناء جمع البيانات.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'سؤال الاستبيان',
                'verbose_name_plural': 'أسئلة الاستبيان',
                'ordering': ['id'],
            },
        ),
    ]
