# Generated by Django 5.2.8 on 2025-12-12 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name_ar', 'name_en']},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='slug',
        ),
        migrations.AlterField(
            model_name='survey',
            name='code',
            field=models.CharField(blank=True, help_text='رمز قصير اختياري مثل LFS_2025.', max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='المستخدمون المسموح لهم بتعديل هيكل الاستبيان.', related_name='editable_surveys', to=settings.AUTH_USER_MODEL, verbose_name='المحررون'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='المسؤول الأساسي عن هذا الاستبيان.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_surveys', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', help_text='مسودة: قيد التصميم. نشط: قيد الاستخدام. مؤرشف: لم يعد مستخدماً.', max_length=20, verbose_name='الحالة'),
        ),
    ]
