# Generated by Django 5.1.3 on 2025-12-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
    ]
