# Generated by Django 5.1.3 on 2025-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name'], 'verbose_name': 'استبيان', 'verbose_name_plural': 'الاستبيانات'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name_en',
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default='Sdasd', max_length=255, unique=True, verbose_name='اسم المسح'),
            preserve_default=False,
        ),
    ]
