# Generated by Django 5.1.3 on 2025-12-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_options_remove_survey_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name_ar', 'name_en'], 'verbose_name': 'استبيان', 'verbose_name_plural': 'الاستبيانات'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ar',
            field=models.CharField(default='sdasd', max_length=255, unique=True, verbose_name='اسم المسح [عربية]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(default='asdasdas', max_length=255, unique=True, verbose_name='اسم المسح [انجليزية]'),
            preserve_default=False,
        ),
    ]
