# Generated by Django 5.2.8 on 2025-12-12 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_options_remove_survey_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='interval',
            field=models.CharField(choices=[('M', 'شهري'), ('Q', 'ربع سنوي'), ('B', 'نصف سنوي'), ('A', 'سنوي')], help_text='تواتر الاستبيان.', max_length=20, verbose_name='الفاصل الزمني'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشط'), ('LOCKED', 'مقفل'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', help_text='مسودة: قابلة للتحرير؛ نشطة: قيد الجمع؛ مقفلة: هيكل ثابت؛ مؤرشفة: للاطلاع التاريخي.', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='version_date',
            field=models.DateField(default=datetime.date.today, help_text='تاريخ الإشارة لهذه النسخة/الموجة.', verbose_name='تاريخ الإصدار'),
        ),
    ]
