# Generated by Django 5.2.8 on 2025-12-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='order',
        ),
    ]
