# Generated by Django 5.1.3 on 2025-12-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_survey_editors_remove_survey_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='section_label',
        ),
    ]
