# Generated by Django 5.1.3 on 2025-12-28 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0003_remove_surveyquestion_section_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyversion',
            name='status',
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='business_logic_done',
            field=models.BooleanField(default=False, verbose_name='منطق الأعمال'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='business_logic_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ منطق الأعمال'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='business_logic_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_logic_surveys', to=settings.AUTH_USER_MODEL, verbose_name='تم منطق الأعمال بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='initial_questionnaire_built',
            field=models.BooleanField(default=False, verbose_name='بناء الاستبيان الأولي'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='initial_questionnaire_built_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البناء'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='initial_questionnaire_built_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='built_initial_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='تم البناء بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='lang_review_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التدقيق'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='lang_review_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_surveys', to=settings.AUTH_USER_MODEL, verbose_name='تم التدقيق بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='lang_review_status',
            field=models.CharField(choices=[('DONE', 'مكتمل'), ('IN_PROGRESS', 'قيد التنفيذ'), ('NO_MANUAL_QUESTIONS', 'لا توجد أسئلة يدوية')], default='IN_PROGRESS', max_length=30, verbose_name='حالة التدقيق اللغوي'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='routing_logic_done',
            field=models.BooleanField(default=False, verbose_name='منطق التوجيه'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='routing_logic_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوجيه'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='routing_logic_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_surveys', to=settings.AUTH_USER_MODEL, verbose_name='تم التوجيه بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='self_assessment_done',
            field=models.BooleanField(default=False, verbose_name='التقييم الذاتي'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='self_assessment_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقييم'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='self_assessment_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_surveys', to=settings.AUTH_USER_MODEL, verbose_name='تم التقييم بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='translation_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترجمة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='translation_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_surveys', to=settings.AUTH_USER_MODEL, verbose_name='تم الترجمة بواسطة'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='translation_status',
            field=models.CharField(choices=[('DONE', 'مكتمل'), ('IN_PROGRESS', 'قيد التنفيذ'), ('NO_MANUAL_QUESTIONS', 'لا توجد أسئلة يدوية')], default='IN_PROGRESS', max_length=30, verbose_name='حالة الترجمة'),
        ),
    ]
