# Generated by Django 5.2.8 on 2025-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_code_alter_surveyversion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name_ar', 'name_en'], 'verbose_name': 'استبيان', 'verbose_name_plural': 'الاستبيانات'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['id'], 'verbose_name': 'سؤال الاستبيان', 'verbose_name_plural': 'أسئلة الاستبيان'},
        ),
        migrations.AlterModelOptions(
            name='surveyversion',
            options={'ordering': ['-version_date', '-id'], 'verbose_name': 'إصدار الاستبيان', 'verbose_name_plural': 'إصدارات الاستبيان'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المسح [عربية]'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المسح [انجليزية]'),
        ),
    ]
