# Generated by Django 6.0 on 2025-12-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='text_ar',
            field=models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة العربية.', verbose_name='النص بالعربية'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='text_en',
            field=models.TextField(blank=True, help_text='النص الكامل للسؤال باللغة الإنجليزية.', verbose_name='النص بالإنجليزية'),
        ),
    ]
