# Generated by Django 5.2.8 on 2025-12-31 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0003_questionstaging_is_sent_for_translation'),
        ('Rbank', '0001_initial'),
        ('surveys', '0004_update_surveyversion_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='is_matrix',
            field=models.BooleanField(default=False, verbose_name='سؤال مصفوفة'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='matrix_item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='Qbank.matrixitemgroup', verbose_name='مجموعة عناصر المصفوفة'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='response_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='Rbank.responsegroup', verbose_name='مجموعة الإجابات'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='response_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='Rbank.responsetype', verbose_name='نوع الإجابة'),
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='عنوان القسم [عربية]')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان القسم [إنجليزية]')),
                ('description_ar', models.TextField(blank=True, verbose_name='وصف القسم [عربية]')),
                ('description_en', models.TextField(blank=True, verbose_name='وصف القسم [إنجليزية]')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'قسم الاستبيان',
                'verbose_name_plural': 'أقسام الاستبيان',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.surveysection', verbose_name='القسم'),
        ),
    ]
