# Generated by Django 5.2.8 on 2025-12-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_update_surveyversion_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyversion',
            name='routing_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='مخطط التوجيه'),
        ),
        migrations.CreateModel(
            name='SurveyRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, verbose_name='الشرط')),
                ('priority', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_survey_rules', to='surveys.surveyquestion', verbose_name='إلى السؤال')),
            ],
            options={
                'verbose_name': 'قاعدة مسار الاستبيان',
                'verbose_name_plural': 'قواعد مسار الاستبيان',
                'ordering': ['to_question_id', 'priority', 'id'],
            },
        ),
    ]
