# Generated by Django 5.2.8 on 2025-12-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_options_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='text',
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
        migrations.AlterField(
            model_name='surveyversion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey', verbose_name='الاستبيان'),
        ),
    ]
