# Generated by Django 5.2.8 on 2025-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_surveyquestion_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='code',
            field=models.CharField(blank=True, help_text='رمز سؤال اختياري مثل Q1 أو A01.', max_length=50, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='section_label',
            field=models.CharField(blank=True, help_text='تسمية قسم منطقية للتقارير فقط.', max_length=255, verbose_name='مسمى القسم'),
        ),
    ]
