# Generated by Django 5.2.9 on 2025-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_surveyquestion_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name_ar',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المسح [عربية]'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المسح [انجليزية]'),
        ),
    ]
