# Generated by Django 5.1.3 on 2025-12-14 19:05

import assessment_flow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_VISITED', 'لم تتم زيارته'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('PENDING_UPLOAD', 'بانتظار رفع ملف')], default='NOT_VISITED', max_length=20, verbose_name='الحالة')),
                ('assessment_path', models.JSONField(blank=True, default=list, verbose_name='مسار التقييم')),
                ('summary_comment', models.TextField(blank=True, verbose_name='تعليق موجز')),
                ('flags', models.JSONField(blank=True, default=dict, verbose_name='أعلام')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='تم تقييمها في')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='تم تقييمها بواسطة')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان')),
            ],
            options={
                'verbose_name': 'نتيجة التقييم',
                'verbose_name_plural': 'نتائج التقييم',
                'ordering': ['assessment_run_id', 'survey_question_id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assessment_flow.models.get_assessment_file_path, verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تم الرفع في')),
                ('triggering_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='assessment_flow.assessmentoption', verbose_name='الخيار المحفز')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessment_files', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment_runs.assessmentresult', verbose_name='نتيجة التقييم')),
            ],
            options={
                'verbose_name': 'ملف التقييم',
                'verbose_name_plural': 'ملفات التقييم',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='تسمية')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأت في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتملت في')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessment_runs', to=settings.AUTH_USER_MODEL, verbose_name='معينة ل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_runs', to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤها بواسطة')),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'عملية تقييم',
                'verbose_name_plural': 'عمليات التقييم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment_runs.assessmentrun', verbose_name='عملية التقييم'),
        ),
        migrations.CreateModel(
            name='QuestionClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('condition', models.TextField(blank=True, help_text='منطق JSON يتم تقييمه بواسطة محرك التصنيف.', verbose_name='الشرط')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف السؤال',
                'verbose_name_plural': 'قواعد تصنيف السؤال',
                'ordering': ['survey_question_id', 'priority', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment_run', 'survey_question')},
        ),
    ]
