# Generated by Django 5.2.8 on 2025-12-12 19:52

import assessment_flow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_VISITED', 'لم تتم زيارته'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('PENDING_UPLOAD', 'بانتظار رفع ملف')], default='NOT_VISITED', max_length=20)),
                ('assessment_path', models.JSONField(blank=True, default=list)),
                ('summary_comment', models.TextField(blank=True)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['assessment_run_id', 'survey_question_id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assessment_flow.models.get_assessment_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggering_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='assessment_flow.assessmentoption')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessment_files', to=settings.AUTH_USER_MODEL)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment_runs.assessmentresult')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessment_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_runs', to=settings.AUTH_USER_MODEL)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment_runs.assessmentrun'),
        ),
        migrations.CreateModel(
            name='QuestionClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100)),
                ('condition', models.TextField(blank=True, help_text='منطق JSON يتم تقييمه بواسطة محرك التصنيف.')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['survey_question_id', 'priority', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment_run', 'survey_question')},
        ),
    ]
