# Generated by Django 5.1.3 on 2025-12-25 23:32

import assessment_runs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='التصنيف [عربية]')),
                ('name_en', models.CharField(max_length=255, verbose_name='التصنيف [إنجليزية]')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='النتائج')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='في')),
                ('classification', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='surveys.surveyquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'نتيجة التقييم',
                'verbose_name_plural': 'نتائج التقييم',
                'ordering': ['assessment_run_id', 'survey_question__code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assessment_runs.models.get_assessment_file_path, verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تم الرفع في')),
                ('triggering_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='assessment_flow.assessmentoption', verbose_name='الخيار المحفز')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessment_files', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment_runs.assessmentresult', verbose_name='نتيجة التقييم')),
            ],
            options={
                'verbose_name': 'ملف التقييم',
                'verbose_name_plural': 'ملفات التقييم',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_run', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'عملية تقييم',
                'verbose_name_plural': 'عمليات التقييم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment_runs.assessmentrun', verbose_name='عملية التقييم'),
        ),
        migrations.CreateModel(
            name='QuestionClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, help_text='منطق JSON يتم تقييمه بواسطة محرك التصنيف.', verbose_name='القاعدة (JSON)')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='assessment_runs.questionclassification', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف',
                'verbose_name_plural': 'قواعد التصنيف',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment_run', 'survey_question')},
        ),
    ]
