# Generated by Django 5.1.3 on 2025-12-14 15:36

import assessment_flow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('assessment_runs', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'ملف التقييم', 'verbose_name_plural': 'ملفات التقييم'},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ['assessment_run_id', 'survey_question_id'], 'verbose_name': 'نتيجة التقييم', 'verbose_name_plural': 'نتائج التقييم'},
        ),
        migrations.AlterModelOptions(
            name='assessmentrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'عملية تقييم', 'verbose_name_plural': 'عمليات التقييم'},
        ),
        migrations.AlterModelOptions(
            name='questionclassificationrule',
            options={'ordering': ['survey_question_id', 'priority', 'id'], 'verbose_name': 'قاعدة تصنيف السؤال', 'verbose_name_plural': 'قواعد تصنيف السؤال'},
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='assessment_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment_runs.assessmentresult', verbose_name='نتيجة التقييم'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(upload_to=assessment_flow.models.get_assessment_file_path, verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='اسم الملف الأصلي'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='triggering_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='assessment_flow.assessmentoption', verbose_name='الخيار المحفز'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تم الرفع في'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessment_files', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تم تقييمها في'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='تم تقييمها بواسطة'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment_path',
            field=models.JSONField(blank=True, default=list, verbose_name='مسار التقييم'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment_runs.assessmentrun', verbose_name='عملية التقييم'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='flags',
            field=models.JSONField(blank=True, default=dict, verbose_name='أعلام'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='status',
            field=models.CharField(choices=[('NOT_VISITED', 'لم تتم زيارته'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('PENDING_UPLOAD', 'بانتظار رفع ملف')], default='NOT_VISITED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='summary_comment',
            field=models.TextField(blank=True, verbose_name='تعليق موجز'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessment_runs', to=settings.AUTH_USER_MODEL, verbose_name='معينة ل'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اكتملت في'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_runs', to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤها بواسطة'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='label',
            field=models.CharField(blank=True, max_length=100, verbose_name='تسمية'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بدأت في'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETE', 'مكتمل'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='classification',
            field=models.CharField(max_length=100, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='condition',
            field=models.TextField(blank=True, help_text='منطق JSON يتم تقييمه بواسطة محرك التصنيف.', verbose_name='الشرط'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان'),
        ),
    ]
