# Generated by Django 5.1.3 on 2025-12-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_runs', '0001_initial'),
        ('surveys', '0003_alter_survey_options_remove_survey_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ['assessment_run_id', 'survey_question__code'], 'verbose_name': 'نتيجة التقييم', 'verbose_name_plural': 'نتائج التقييم'},
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='assessment_path',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='summary_comment',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='label',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='assessmentrun',
            name='status',
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='classification',
            field=models.CharField(blank=True, max_length=100, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='results',
            field=models.JSONField(blank=True, default=list, verbose_name='النتائج'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='في'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='surveys.surveyquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='assessmentrun',
            name='survey_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_run', to='surveys.surveyversion', verbose_name='إصدار الاستبيان'),
        ),
    ]
