# Generated by Django 5.2.8 on 2025-12-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_runs', '0001_initial'),
        ('surveys', '0003_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100)),
                ('condition', models.TextField(blank=True, help_text='JSON logic evaluated by the ClassificationEngine.')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['survey_question_id', 'priority', 'id'],
            },
        ),
    ]
