# Generated by Django 5.1.3 on 2025-12-25 14:53

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_runs', '0002_alter_assessmentresult_options_and_more'),
    ]

    operations = []
