# Generated by Django 5.1.3 on 2025-12-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_runs', '0002_alter_assessmentresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='التصنيف [عربية]')),
                ('name_en', models.CharField(max_length=255, verbose_name='التصنيف [إنجليزية]')),
            ],
            options={
                'verbose_name': 'تصنيف السؤال',
                'verbose_name_plural': 'تصنيفات الأسئلة',
            },
        ),
        migrations.AlterModelOptions(
            name='questionclassificationrule',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'قاعدة تصنيف', 'verbose_name_plural': 'قواعد التصنيف'},
        ),
        migrations.AlterField(
            model_name='questionclassificationrule',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='assessment_runs.questionclassification', verbose_name='التصنيف'),
        ),
    ]
