# Generated by Django 5.2.8 on 2025-12-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('STATIC', 'خيارات ثابتة'), ('DYNAMIC_FROM_PREVIOUS_MULTI_SELECT', 'ديناميكي (من اختيار متعدد سابق)'), ('DYNAMIC_SURVEY_QUESTIONS', 'ديناميكي (أسئلة الاستبيان)'), ('INDICATOR_LIST', 'قائمة المؤشرات')], default='STATIC', max_length=50)),
                ('use_searchable_dropdown', models.BooleanField(default=False)),
                ('allow_multiple_choices', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('dynamic_option_source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion', verbose_name='Dynamic Option Source Question')),
                ('indicator_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator', verbose_name='Indicator Source')),
                ('survey_question', models.OneToOneField(blank=True, help_text='سؤال الاستبيان الرئيسي الذي يمثله هذا العقد في التقييم.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question', to='surveys.surveyquestion', verbose_name='سؤال الاستبيان')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text="قيمة الخيار، مثلاً 'option_1' أو 'نعم' أو 'غير ذلك'", max_length=255)),
                ('response_type', models.CharField(choices=[('PREDEFINED', 'خيار محدد مسبقاً'), ('FREE_TEXT', 'إدخال نصي حر'), ('NUMERICAL', 'إدخال رقمي'), ('URL', 'إدخال رابط')], default='PREDEFINED', max_length=20)),
                ('requires_file_upload', models.BooleanField(default=False)),
                ('file_upload_explanation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment_flow.assessmentquestion')),
            ],
            options={
                'verbose_name': 'Assessment Option',
                'verbose_name_plural': 'Assessment Options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFlowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"', verbose_name='Condition')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='assessment_flow.assessmentquestion', verbose_name='From Question')),
            ],
            options={
                'verbose_name': 'Assessment Flow Rule',
                'verbose_name_plural': 'Assessment Flow Rules',
                'ordering': ['from_question_id', 'priority'],
            },
        ),
    ]
