# Generated by Django 5.2.8 on 2025-12-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation for assessors.')),
                ('option_type', models.CharField(choices=[('STATIC', 'Static Options'), ('DYNAMIC_FROM_PREVIOUS_MULTI_SELECT', 'Dynamic (from previous multi-select)'), ('DYNAMIC_SURVEY_QUESTIONS', 'Dynamic (Survey Questions)')], default='STATIC', max_length=50)),
                ('use_searchable_dropdown', models.BooleanField(default=False)),
                ('allow_multiple_choices', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_option_source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('response_type', models.CharField(choices=[('PREDEFINED', 'Predefined Choice'), ('FREE_TEXT', 'Free Text Input'), ('NUMERICAL', 'Numerical Input'), ('URL', 'URL Input')], default='PREDEFINED', max_length=20)),
                ('requires_file_upload', models.BooleanField(default=False)),
                ('file_upload_explanation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment_flow.assessmentquestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFlowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, help_text='Expression to be evaluated by the routing engine. E.g., "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='assessment_flow.assessmentquestion')),
            ],
            options={
                'ordering': ['from_question_id', 'priority'],
            },
        ),
    ]
