# Generated by Django 5.1.3 on 2025-12-31 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(blank=True, max_length=512, verbose_name='السؤال [عربية]')),
                ('text_en', models.CharField(blank=True, max_length=512, verbose_name='السؤال [إنجليزية]')),
                ('explanation_ar', models.TextField(blank=True, verbose_name='التوضيح [عربية]')),
                ('explanation_en', models.TextField(blank=True, verbose_name='التوضيح [إنجليزية]')),
                ('option_type', models.CharField(choices=[('STATIC', 'خيارات ثابتة'), ('DYNAMIC_FROM_PREVIOUS_MULTI_SELECT', 'ديناميكي (من اختيار متعدد سابق)'), ('DYNAMIC_SURVEY_QUESTIONS', 'ديناميكي (أسئلة الاستبيان)'), ('INDICATOR_LIST', 'قائمة المؤشرات')], default='STATIC', max_length=50, verbose_name='نوع الخيار')),
                ('use_searchable_dropdown', models.BooleanField(default=False, verbose_name='استخدام قائمة منسدلة قابلة للبحث')),
                ('allow_multiple_choices', models.BooleanField(default=False, verbose_name='السماح باختيارات متعددة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('dynamic_option_source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion', verbose_name='سؤال مصدر الخيارات الديناميكي')),
                ('indicator_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator', verbose_name='مصدر المؤشر')),
            ],
            options={
                'verbose_name': 'سؤال التقييم',
                'verbose_name_plural': 'أسئلة التقييم',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(blank=True, verbose_name='الجواب [عربية]')),
                ('text_en', models.TextField(blank=True, verbose_name='الجواب [إنجليزية]')),
                ('explanation_ar', models.TextField(blank=True, verbose_name='التوضيح [عربية]')),
                ('explanation_en', models.TextField(blank=True, verbose_name='التوضيح [إنجليزية]')),
                ('response_type', models.CharField(choices=[('PREDEFINED', 'خيار محدد مسبقاً'), ('FREE_TEXT', 'إدخال نصي حر'), ('NUMERICAL', 'إدخال رقمي'), ('URL', 'إدخال رابط')], default='PREDEFINED', max_length=20, verbose_name='نوع الاستجابة')),
                ('requires_file_upload', models.BooleanField(default=False)),
                ('file_upload_explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment_flow.assessmentquestion')),
            ],
            options={
                'verbose_name': 'خيار التقييم',
                'verbose_name_plural': 'خيارات التقييم',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFlowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, verbose_name='الشرط')),
                ('priority', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='assessment_flow.assessmentquestion', verbose_name='إلى السؤال')),
            ],
            options={
                'verbose_name': 'قاعدة مسار التقييم',
                'verbose_name_plural': 'قواعد مسار التقييم',
                'ordering': ['to_question_id', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ReevaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(blank=True, max_length=512, verbose_name='السؤال [عربية]')),
                ('text_en', models.CharField(blank=True, max_length=512, verbose_name='السؤال [إنجليزية]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluation_questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'سؤال إعادة التقييم',
                'verbose_name_plural': 'اسئلة إعادة التقييم',
                'ordering': ['id'],
            },
        ),
    ]
