# Generated by Django 5.2.8 on 2025-12-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='indicator_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='option_type',
            field=models.CharField(choices=[('STATIC', 'Static Options'), ('DYNAMIC_FROM_PREVIOUS_MULTI_SELECT', 'Dynamic (from previous multi-select)'), ('DYNAMIC_SURVEY_QUESTIONS', 'Dynamic (Survey Questions)'), ('INDICATOR_LIST', 'Indicator List')], default='STATIC', max_length=50),
        ),
    ]
