# Generated by Django 5.1.3 on 2025-12-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentflowrule',
            options={'ordering': ['to_question_id', 'priority'], 'verbose_name': 'قاعدة مسار التقييم', 'verbose_name_plural': 'قواعد مسار التقييم'},
        ),
        migrations.AlterModelOptions(
            name='assessmentoption',
            options={'ordering': ['id'], 'verbose_name': 'خيار التقييم', 'verbose_name_plural': 'خيارات التقييم'},
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='assessment_flow.assessmentquestion', verbose_name='إلى السؤال'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='reevaluationquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='reevaluationquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
