# Generated by Django 5.2.8 on 2025-12-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentflowrule',
            options={'ordering': ['from_question_id', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='assessmentoption',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='assessmentoption',
            name='value',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='survey_question',
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='explanation_ar',
            field=models.TextField(blank=True, verbose_name='التوضيح [عربية]'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='التوضيح [إنجليزية]'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='text_ar',
            field=models.TextField(blank=True, verbose_name='السؤال [عربية]'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='السؤال [إنجليزية]'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='توضيح اختياري للمقيّمين.'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='explanation_ar',
            field=models.TextField(blank=True, verbose_name='التوضيح [عربية]'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='التوضيح [إنجليزية]'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='text',
            field=models.CharField(default='asda', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='text_ar',
            field=models.CharField(blank=True, max_length=512, verbose_name='السؤال [عربية]'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='text_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='السؤال [إنجليزية]'),
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='condition',
            field=models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"'),
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='from_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='assessment_flow.assessmentquestion'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='dynamic_option_source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='indicator_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
