# Generated by Django 6.0 on 2025-12-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0002_assessmentquestion_indicator_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoption',
            name='explanation_ar',
            field=models.TextField(blank=True, verbose_name='التوضيح بالعربية'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='التوضيح بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='text_ar',
            field=models.TextField(blank=True, verbose_name='النص بالعربية'),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='النص بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='explanation_ar',
            field=models.TextField(blank=True, verbose_name='التوضيح بالعربية'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='التوضيح بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='text_ar',
            field=models.CharField(blank=True, max_length=512, verbose_name='النص بالعربية'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='text_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='النص بالإنجليزية'),
        ),
    ]
