# Generated by Django 5.2.8 on 2025-12-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0002_alter_assessmentflowrule_options_and_more'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentflowrule',
            options={'ordering': ['from_question_id', 'priority'], 'verbose_name': 'Assessment Flow Rule', 'verbose_name_plural': 'Assessment Flow Rules'},
        ),
        migrations.AlterModelOptions(
            name='assessmentoption',
            options={'ordering': ['id'], 'verbose_name': 'Assessment Option', 'verbose_name_plural': 'Assessment Options'},
        ),
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['id'], 'verbose_name': 'Assessment Question', 'verbose_name_plural': 'Assessment Questions'},
        ),
        migrations.RemoveField(
            model_name='assessmentoption',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='assessmentoption',
            name='text',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='text',
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='condition',
            field=models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='from_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='assessment_flow.assessmentquestion', verbose_name='From Question'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='dynamic_option_source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion', verbose_name='Dynamic Option Source Question'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='indicator_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator', verbose_name='Indicator Source'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
