# Generated by Django 5.2.8 on 2025-12-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0003_alter_assessmentflowrule_options_and_more'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='condition',
            field=models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"', verbose_name='قاعدة توجيه'),
        ),
        migrations.AlterField(
            model_name='assessmentoption',
            name='response_type',
            field=models.CharField(choices=[('PREDEFINED', 'خيار محدد مسبقاً'), ('FREE_TEXT', 'إدخال نصي حر'), ('NUMERICAL', 'إدخال رقمي'), ('URL', 'إدخال رابط')], default='PREDEFINED', max_length=20, verbose_name='نوع الاستجابة'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='allow_multiple_choices',
            field=models.BooleanField(default=False, verbose_name='السماح باختيارات متعددة'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='dynamic_option_source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_option_consumers', to='assessment_flow.assessmentquestion', verbose_name='سؤال مصدر الخيارات الديناميكي'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='indicator_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='indicators.indicator', verbose_name='مصدر المؤشر'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='option_type',
            field=models.CharField(choices=[('STATIC', 'خيارات ثابتة'), ('DYNAMIC_FROM_PREVIOUS_MULTI_SELECT', 'ديناميكي (من اختيار متعدد سابق)'), ('DYNAMIC_SURVEY_QUESTIONS', 'ديناميكي (أسئلة الاستبيان)'), ('INDICATOR_LIST', 'قائمة المؤشرات')], default='STATIC', max_length=50, verbose_name='نوع الخيار'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='use_searchable_dropdown',
            field=models.BooleanField(default=False, verbose_name='استخدام قائمة منسدلة قابلة للبحث'),
        ),
    ]
