# Generated by Django 5.2.8 on 2025-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0004_alter_assessmentflowrule_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['id'], 'verbose_name': 'سؤال التقييم', 'verbose_name_plural': 'أسئلة التقييم'},
        ),
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='condition',
            field=models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"', verbose_name='الشرط'),
        ),
    ]
