# Generated by Django 5.2.8 on 2025-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0005_alter_assessmentquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentoption',
            name='text_ar',
            field=models.TextField(blank=True, verbose_name='الجواب [عربية]'),
        ),
        migrations.AlterField(
            model_name='assessmentoption',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='الجواب [إنجليزية]'),
        ),
    ]
