# Generated by Django 5.2.8 on 2025-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0006_alter_assessmentoption_text_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentflowrule',
            name='condition',
            field=models.TextField(blank=True, help_text='تعبير يُقيّمه محرك التوجيه، مثل "option == \'CODE_A\' -> \'NEXT_Q_CODE\'"', verbose_name='الشرط'),
        ),
    ]
