# Generated by Django 5.1.3 on 2025-12-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_flow', '0007_alter_assessmentflowrule_condition'),
        ('surveys', '0007_alter_survey_name_ar_alter_survey_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReevaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(blank=True, max_length=512, verbose_name='السؤال [عربية]')),
                ('text_en', models.CharField(blank=True, max_length=512, verbose_name='السؤال [إنجليزية]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluation_questions', to='surveys.surveyversion', verbose_name='إصدار الاستبيان')),
            ],
            options={
                'verbose_name': 'سؤال إعادة التقييم',
                'verbose_name_plural': 'اسئلة إعادة التقييم',
                'ordering': ['id'],
            },
        ),
    ]
