# Generated by Django 5.1.3 on 2025-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=255, verbose_name='الجواب [عربية]')),
                ('text_en', models.CharField(max_length=255, verbose_name='الجواب [إنجليزية]')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'إجابات',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='نوع الاستجابة [عربية]')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='نوع الاستجابة [إنجليزية]')),
            ],
            options={
                'verbose_name': 'نوع الاستجابة',
                'verbose_name_plural': 'أنواع الاستجابة',
            },
        ),
        migrations.CreateModel(
            name='ResponseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('responses', models.ManyToManyField(to='Rbank.response', verbose_name='الإجابات')),
            ],
            options={
                'verbose_name': 'مجموعة إجابات',
                'verbose_name_plural': 'مجموعات الإجابات',
            },
        ),
    ]
